name: Build Cordova Android
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.4

    - name: Install Node
      uses: actions/setup-node@v2.2.4
      with:
        node-version: 16

    - name: Install Java
      uses: actions/setup-java@v2.2.4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Install Dependencies
      run: npm install

    - name: Add Android Platform
      run: cordova platform add android

    - name: Build Android
      run: cordova build android --release

    
